name: instagram_copy
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.2
  cloud_functions: ^4.5.8
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  multiple_result: ^5.1.0
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: any
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/ig_logo.png
    - assets/images/my_photo.jpg
    - assets/images/Meta-Logo.png

  fonts:
    - family: AltFont
      fonts:
        - asset: assets/fonts/ig_sans_font/Instagram_Sans_Headline.ttf
    - family: Instagram_Sans
      fonts:
        - asset: assets/fonts/ig_sans_font/Instagram_Sans_Regular.ttf
        - asset: assets/fonts/ig_sans_font/Instagram_Sans_Light.ttf
        - asset: assets/fonts/ig_sans_font/Instagram_Sans_Medium.ttf
    - family: Karmela
      fonts:
        - asset: assets/fonts/karmela_font/Karmela_Regular.ttf
