// Mocks generated by Mockito 5.4.4 from annotations
// in instagram_copy/test/lib/src/features/authentication/domain/controllers/persisted_users_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:instagram_copy/src/features/authentication/data/entities/user_entity.dart'
    as _i5;
import 'package:instagram_copy/src/features/authentication/data/persisted_users_repository.dart'
    as _i3;
import 'package:instagram_copy/src/features/authentication/domain/controllers/persisted_users_controller.dart'
    as _i6;
import 'package:instagram_copy/src/features/authentication/domain/models/user.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeAsyncNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeAsyncNotifierProviderRef<T> {
  _FakeAutoDisposeAsyncNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_1<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersistedUsersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistedUsersRepository extends _i1.Mock
    implements _i3.PersistedUsersRepository {
  @override
  _i4.Future<void> addUser(_i5.UserEntity? entity) => (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [entity],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [uid],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.UserEntity>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.UserEntity>>.value(<_i5.UserEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.UserEntity>>.value(<_i5.UserEntity>[]),
      ) as _i4.Future<List<_i5.UserEntity>>);
}

/// A class which mocks [PersistedUsersController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistedUsersController extends _i1.Mock
    implements _i6.PersistedUsersController {
  @override
  _i2.AutoDisposeAsyncNotifierProviderRef<List<_i7.UserModel>> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue:
            _FakeAutoDisposeAsyncNotifierProviderRef_0<List<_i7.UserModel>>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeAutoDisposeAsyncNotifierProviderRef_0<List<_i7.UserModel>>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.AutoDisposeAsyncNotifierProviderRef<List<_i7.UserModel>>);

  @override
  _i2.AsyncValue<List<_i7.UserModel>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_1<List<_i7.UserModel>>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAsyncValue_1<List<_i7.UserModel>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<List<_i7.UserModel>>);

  @override
  set state(_i2.AsyncValue<List<_i7.UserModel>>? newState) =>
      super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i7.UserModel>> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
      ) as _i4.Future<List<_i7.UserModel>>);

  @override
  _i4.Future<List<_i7.UserModel>> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
      ) as _i4.Future<List<_i7.UserModel>>);

  @override
  _i4.Future<void> addCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #addCurrentUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [uid],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.UserModel>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
      ) as _i4.Future<List<_i7.UserModel>>);

  @override
  _i4.Future<List<_i7.UserModel>> update(
    _i4.FutureOr<List<_i7.UserModel>> Function(List<_i7.UserModel>)? cb, {
    _i4.FutureOr<List<_i7.UserModel>> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.UserModel>>.value(<_i7.UserModel>[]),
      ) as _i4.Future<List<_i7.UserModel>>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<List<_i7.UserModel>>? previous,
    _i2.AsyncValue<List<_i7.UserModel>>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
