// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDieC68HlrNRx-_UENdroF8PgLJL3lEtWM',
    appId: '1:540636352956:web:92ef98a413da303b96dbb9',
    messagingSenderId: '540636352956',
    projectId: 'instagram-copy-c694f',
    authDomain: 'instagram-copy-c694f.firebaseapp.com',
    storageBucket: 'instagram-copy-c694f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaycHcKxD7ORStK76whMGsWmROJvJaq0c',
    appId: '1:540636352956:android:528240229d7fbc8196dbb9',
    messagingSenderId: '540636352956',
    projectId: 'instagram-copy-c694f',
    storageBucket: 'instagram-copy-c694f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKEFqhjcMPBnyaPzCaMLlKph3t0PRTF8',
    appId: '1:540636352956:ios:e27b6477063624e096dbb9',
    messagingSenderId: '540636352956',
    projectId: 'instagram-copy-c694f',
    storageBucket: 'instagram-copy-c694f.appspot.com',
    iosBundleId: 'com.example.instagramCopy',
  );
}
